servermake: main_server.c serverclientlib.c serverlib.c socklib.c epolllib.c double_list.c patricia.c signals.c tlv.c
	gcc -o server main_server.c serverclientlib.c serverlib.c socklib.c epolllib.c double_list.c patricia.c signals.c tlv.c -I.
