servermake: main_server.c serverclientlib.c serverlib.c socklib.c epolllib.c double_list.c patricia.c signals.c tlv.c cli.c
	gcc  -pthread -o server main_server.c serverclientlib.c serverlib.c socklib.c epolllib.c double_list.c patricia.c signals.c tlv.c cli.c -I.
