servermake: main_server.c serverclientlib.c serverlib.c socklib.c epolllib.c double_list.c patricia.c
	gcc -o server main_server.c serverclientlib.c serverlib.c socklib.c epolllib.c double_list.c patricia.c -I.
